# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../blackzspace.de-Main/blackzspace.de-reactjs-app-v8/build/favicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_Image = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_Image.setGeometry(QtCore.QRect(100, 140, 321, 25))
        self.output_Image.setObjectName("output_Image")
        self.set_Output_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.set_Output_Button.setGeometry(QtCore.QRect(430, 140, 80, 25))
        self.set_Output_Button.setObjectName("set_Output_Button")
        self.label_output_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_output_image.setGeometry(QtCore.QRect(100, 120, 121, 17))
        self.label_output_image.setObjectName("label_output_image")
        self.label_device = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_device.setGeometry(QtCore.QRect(100, 190, 121, 17))
        self.label_device.setObjectName("label_device")
        self.comboBox_devices = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_devices.setGeometry(QtCore.QRect(100, 210, 181, 25))
        self.comboBox_devices.setObjectName("comboBox_devices")
        self.build_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.build_Button.setGeometry(QtCore.QRect(430, 210, 80, 25))
        self.build_Button.setObjectName("build_Button")
        self.consoleLog = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.consoleLog.setGeometry(QtCore.QRect(0, 320, 801, 211))
        self.consoleLog.setObjectName("consoleLog")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 540, 801, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.scan_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.scan_Button.setGeometry(QtCore.QRect(290, 210, 80, 25))
        self.scan_Button.setObjectName("scan_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "blackzspace Imager || (c) by BlackLeakz"))
        self.set_Output_Button.setText(_translate("MainWindow", "Set"))
        self.label_output_image.setText(_translate("MainWindow", "Output Image:"))
        self.label_device.setText(_translate("MainWindow", "Device"))
        self.build_Button.setText(_translate("MainWindow", "Build"))
        self.scan_Button.setText(_translate("MainWindow", "Scan"))
